language: node_js
rvm:
  - 1.9.3
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - bundle install
  - npm install
  - bower install
script:
  - grunt travis



